# Generated by Django 6.0.6 on 2026-06-28 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresTroncon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inspection', models.DateField(verbose_name="Date de l'auscultation")),
                ('id0_vizir', models.IntegerField(help_text='Entier de 0 à 7', verbose_name='Indice VIZIR observé (Is = ID₀)')),
                ('mode_A', models.CharField(choices=[('direct', 'Valeur directe'), ('detaille', 'Calcul détaillé')], default='direct', max_length=10, verbose_name='Mode saisie A')),
                ('A', models.FloatField(blank=True, null=True, verbose_name='Agressivité du trafic (A)')),
                ('N_PL', models.FloatField(blank=True, null=True, verbose_name='Nombre cumulé de poids lourds (N_PL)')),
                ('CAM', models.FloatField(blank=True, null=True, verbose_name="Coefficient d'agressivité moyen (CAM)")),
                ('Nref', models.FloatField(blank=True, null=True, verbose_name="Nombre d'essieux de référence (Nref)")),
                ('mode_CL', models.CharField(choices=[('direct', 'Valeur directe'), ('detaille', 'Calcul détaillé')], default='direct', max_length=10, verbose_name='Mode saisie CL')),
                ('CL', models.FloatField(blank=True, null=True, verbose_name='Coefficient climatique (CL)')),
                ('P', models.FloatField(blank=True, null=True, verbose_name='Pluviométrie normalisée (P)')),
                ('T', models.FloatField(blank=True, null=True, verbose_name='Température normalisée (T)')),
                ('H', models.FloatField(blank=True, null=True, verbose_name='Humidité normalisée (H)')),
                ('w1', models.FloatField(blank=True, default=0.4, null=True, verbose_name='Poids w1 (pluviométrie)')),
                ('w2', models.FloatField(blank=True, default=0.35, null=True, verbose_name='Poids w2 (température)')),
                ('w3', models.FloatField(blank=True, default=0.25, null=True, verbose_name='Poids w3 (humidité)')),
                ('mode_M', models.CharField(choices=[('direct', 'Valeur directe'), ('detaille', 'Calcul détaillé')], default='direct', max_length=10, verbose_name='Mode saisie M')),
                ('M', models.FloatField(blank=True, null=True, verbose_name='Paramètre matériau (M)')),
                ('CBR', models.FloatField(blank=True, null=True, verbose_name='Indice CBR (%)')),
                ('eref', models.FloatField(blank=True, null=True, verbose_name='Épaisseur de référence (cm)')),
                ('dc_deflexion', models.FloatField(blank=True, null=True, verbose_name='Déflexion caractéristique dc (1/100 mm)')),
                ('degradations_observees', models.TextField(blank=True, help_text='Ex. faïençage, nid de poule, orniérage...', verbose_name='Types de dégradations observées')),
            ],
            options={
                'verbose_name': "Paramètres d'inspection",
                'verbose_name_plural': "Paramètres d'inspection",
                'ordering': ['-date_inspection'],
            },
        ),
        migrations.CreateModel(
            name='Troncon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Identifiant du tronçon')),
                ('route', models.CharField(blank=True, max_length=200, verbose_name='Nom de la route')),
                ('pk_debut', models.CharField(blank=True, max_length=50, verbose_name='PK début')),
                ('pk_fin', models.CharField(blank=True, max_length=50, verbose_name='PK fin')),
                ('longueur_m', models.FloatField(blank=True, null=True, verbose_name='Longueur (m)')),
                ('localisation', models.CharField(blank=True, max_length=300, verbose_name='Localisation / pays')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tronçon',
                'verbose_name_plural': 'Tronçons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ResultatsSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateTimeField(default=django.utils.timezone.now)),
                ('R', models.FloatField(verbose_name='Rythme de dégradation R (pts/an)')),
                ('contrib_trafic', models.FloatField()),
                ('contrib_climat', models.FloatField()),
                ('contrib_materiau', models.FloatField()),
                ('contrib_trafic_pct', models.FloatField(default=0)),
                ('contrib_climat_pct', models.FloatField(default=0)),
                ('contrib_materiau_pct', models.FloatField(default=0)),
                ('facteur_dominant', models.CharField(max_length=50)),
                ('niveau_risque', models.CharField(max_length=20)),
                ('t_critique_ans', models.FloatField(null=True, verbose_name='Temps avant ID=7 (années)')),
                ('projections_json', models.JSONField(default=dict, verbose_name='Projections ID(t)')),
                ('recommandations', models.TextField()),
                ('alpha_utilise', models.FloatField(default=0.4)),
                ('beta_utilise', models.FloatField(default=0.35)),
                ('gamma_utilise', models.FloatField(default=0.25)),
                ('parametres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='troncons.parametrestroncon')),
                ('troncon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='troncons.troncon')),
            ],
            options={
                'verbose_name': 'Résultats de simulation',
                'verbose_name_plural': 'Résultats de simulation',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.AddField(
            model_name='parametrestroncon',
            name='troncon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='troncons.troncon'),
        ),
        migrations.CreateModel(
            name='CoefficientsSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField(default=0.4, verbose_name='α (trafic)')),
                ('beta', models.FloatField(default=0.35, verbose_name='β (climat)')),
                ('gamma', models.FloatField(default=0.25, verbose_name='γ (matériau)')),
                ('seuil_critique_ans', models.FloatField(default=2.0, verbose_name='Seuil Critique (années)')),
                ('seuil_eleve_ans', models.FloatField(default=10.0, verbose_name='Seuil Élevé (années)')),
                ('troncon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='troncons.troncon')),
            ],
            options={
                'verbose_name': 'Coefficients de simulation',
            },
        ),
    ]
